- name: Web Server Deploy Playbook
  hosts: ansible-hosts
  tasks:
  - name: install httpd
    package: 
      name: apache2 
      state: present
  - name: copy index.html
    copy: 
      dest: /var/www/html/index.html
      content: <!DOCTYPE html>
          <html>
          <body>
          <p>Hello World from SJSU-"{{ server_name }}"</p>
          </body>
          </html>
  - name: start httpd
    service:
      name: apache2 
      state: started